export const SET_USER = "SET_USER";
export const ADD_MARKER = "ADD_MARKER"
export const REMOVE_STOPPAGE = "REMOVE_STOPPAGE"
export const ADD_STOPPAGE = "ADD_STOPPAGE"
export const SET_STOPPAGES = "SET_STOPPAGES" 
export const SET_STOPPAGE = "SET_STOPPAGE"
export const SET_BUS_ROUTE = "SET_BUS_ROUTE"
export const SET_BUS_DATA = "SET_BUS_DATA"
export const SET_BUSES = "SET_BUSES" 

export const LEADING_POS = [24.86954406090458, 91.8049602415959]


