export const SET_EDITING_BUS = "SET_EDITING_BUS"
export const SET_LOADING = "SET_LOADING"
export const EDITING_BUS = "EDITING_BUS"
export const ADDING_STOPPAGE = "ADDING_STOPPAGE"
export const DEFAULT = "DEFAULT"
export const LOADING = "LOADING"